name: 'resume-analyzer'

services:
  api:
      container_name: resume_analyzer_api
      build: .
      restart: unless-stopped
      env_file:
        - .env
      ports:
        - "8000:8000"
      depends_on:
        - mongo
      networks:
        - resume_analyzer_network

  celery:
    container_name: celery
    build: .
    command: celery --app celery_app.config.app worker --loglevel=info --pool=prefork
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    networks:
      - resume_analyzer_network

  redis:
    image: redis:alpine
    container_name: resume_analyzer_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - resume_analyzer_network
    volumes:
      - redis_data:/data
 
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    networks:
      - resume_analyzer_network

  ollama:
    build: ./ollama
    ports:
      - 11434:11434
    volumes:
      - ollama_vol:/ollama
    networks:
      - resume_analyzer_network
    entrypoint: [ "/usr/bin/bash", "pull-llama3.sh" ]

networks:
  resume_analyzer_network:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
  ollama_vol:
